# Generated by Django 5.1.4 on 2025-01-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_youtube_url_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='testimo/'),
        ),
    ]
